apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: landing-page
build:
  artifacts:
  - image: landing-page
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/ingress.yaml
