apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: landingpage-ingress
  namespace: upphandling
  annotations:
    kubernetes.io/ingress.class: "public"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/http2-push-preload: "true"
spec:
  tls:
  - hosts:
    - upphandling.app
    secretName: landingpage-prod-tls
  rules:
  - host: upphandling.app
    http:
      paths:
      - backend:
          serviceName: landingpage
          servicePort: 80